// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKsDIx7b4nT962YAtSSjX2XOa_TYzTTyM',
    appId: '1:878563891622:web:2114bdf89f7ab412385767',
    messagingSenderId: '878563891622',
    projectId: 'logindemo-e1573',
    authDomain: 'logindemo-e1573.firebaseapp.com',
    storageBucket: 'logindemo-e1573.firebasestorage.app',
    measurementId: 'G-NPDCVQ2LKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflSUlLuWLrLipYNnjldJRNJkaYBUQ-CM',
    appId: '1:878563891622:android:786390a824949941385767',
    messagingSenderId: '878563891622',
    projectId: 'logindemo-e1573',
    storageBucket: 'logindemo-e1573.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6VrudN4EqYtQ-lp7DrWLKAaHJAx_0bIw',
    appId: '1:878563891622:ios:cf4ee8fcdbae684d385767',
    messagingSenderId: '878563891622',
    projectId: 'logindemo-e1573',
    storageBucket: 'logindemo-e1573.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6VrudN4EqYtQ-lp7DrWLKAaHJAx_0bIw',
    appId: '1:878563891622:ios:cf4ee8fcdbae684d385767',
    messagingSenderId: '878563891622',
    projectId: 'logindemo-e1573',
    storageBucket: 'logindemo-e1573.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKsDIx7b4nT962YAtSSjX2XOa_TYzTTyM',
    appId: '1:878563891622:web:4026220eaeb8dcd3385767',
    messagingSenderId: '878563891622',
    projectId: 'logindemo-e1573',
    authDomain: 'logindemo-e1573.firebaseapp.com',
    storageBucket: 'logindemo-e1573.firebasestorage.app',
    measurementId: 'G-EHT5T6R5NK',
  );
}
