// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuGCJ8Q7oMbKeQm5SYDaccNpDbNRfb0U',
    appId: '1:772163256790:web:962ed573c1f692a9f0e477',
    messagingSenderId: '772163256790',
    projectId: 'moviles2-7c955',
    authDomain: 'moviles2-7c955.firebaseapp.com',
    storageBucket: 'moviles2-7c955.firebasestorage.app',
    measurementId: 'G-BRG1F3DS4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwDP7ul2oYZz6O4K56TM2pZ8qP8SThPJY',
    appId: '1:772163256790:android:a68b6d275a902209f0e477',
    messagingSenderId: '772163256790',
    projectId: 'moviles2-7c955',
    storageBucket: 'moviles2-7c955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVvx1a7Kve3LeI1n7vJbPgSSuoQgM_8g',
    appId: '1:772163256790:ios:07c5805fcb2ce35cf0e477',
    messagingSenderId: '772163256790',
    projectId: 'moviles2-7c955',
    storageBucket: 'moviles2-7c955.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWVvx1a7Kve3LeI1n7vJbPgSSuoQgM_8g',
    appId: '1:772163256790:ios:07c5805fcb2ce35cf0e477',
    messagingSenderId: '772163256790',
    projectId: 'moviles2-7c955',
    storageBucket: 'moviles2-7c955.firebasestorage.app',
    iosBundleId: 'com.example.productListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHuGCJ8Q7oMbKeQm5SYDaccNpDbNRfb0U',
    appId: '1:772163256790:web:49b7eafefd2ea35cf0e477',
    messagingSenderId: '772163256790',
    projectId: 'moviles2-7c955',
    authDomain: 'moviles2-7c955.firebaseapp.com',
    storageBucket: 'moviles2-7c955.firebasestorage.app',
    measurementId: 'G-1WPDP68S4W',
  );

}